spring:
  application:
    name: test
  profiles:
    default: aws_cloud
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB

server:
  address: 0.0.0.0
  port: 8080

cloud:
  aws:
    region:
      static: us-east-1