cloud:
  aws:
    s3:
      bucket: full-stack-anirudh-test-dev
    secretsmanager:
      secret-name: fullstack-app/dev/rds/credentials

spring:
  datasource:
    url: jdbc:mysql://fullstack-app-dev-nlb-774eb43df9b6b71e.elb.us-east-1.amazonaws.com:3306/anirudhrevalli
    username: root

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect